### ISSUE TITLE
crash app in real device !

### ISSUE THREAD

**Issue by hhhbk** [Jacse/react-native-app-intro-slider#11] opened 2017-12-31 21:20 UTC
I use app intro on my emulator and its ok, but when i release my app and run it in real device ( any android device ) my app is crashing...

**Comment by Jacse** [comment] 2018-01-02 06:19
Hi @hhhbk 

Do you have any sort of error reporting og logs you could post?

**Comment by hhhbk** [comment] 2018-01-04 11:25
Hi @Jacse 

I reinstalled the package , this time my app does not crash,
But it just shows a white screen when i use "AppIntroSlider" component in my code , I install debug version and show me this error ..

![screenshot_2018-01-03-23-51-20](https://user-images.githubusercontent.com/14168242/34561347-c7ae24f4-f15e-11e7-9e3e-412acf4d1690.png)

![screenshot_2018-01-03-23-51-32](https://user-images.githubusercontent.com/14168242/34561352-cd698eba-f15e-11e7-95b2-903c62e0a9ce.png)


I use version 0.51.0 of react native

**Comment by Jacse** [comment] 2018-01-04 16:18
@hhhbk why do you think this component is causing the crash? What I gather from the error reporting is that it is caused by an error in your code somewhere.

**Comment by hhhbk** [comment] 2018-01-05 12:25
the problem was not from code, I just copied the example code and got error , but I found the problem , I downgrade my react native version to 0.49 and the problem got fixed , thanks for the app intro .

**Comment by Jacse** [comment] 2018-01-05 13:50
Okay, closing since the issue is unrelated to the component.

**Closed by Jacse** 2018-01-05 13:50 UTC
