### ISSUE TITLE
OnSwipe event

### ISSUE THREAD

**Issue by dipo1** [Jacse/react-native-app-intro-slider#146] opened 2019-10-22 22:47 UTC
I will like to transition into another screen with react-navigation-transition when a user swipe-left on the last slide.

I couldn't achieve this with the onSlideChange, onDone and onSkip events, unfortunately.

Can we have an onSwipe event?

**Comment by Jacse** [comment] 2019-10-23 07:19
Why doesn't it work if you listen to  `onSlideChange` and check when a user swipes to the last screen?

**Comment by ymcewen** [comment] 2019-10-29 12:14
Hi- just want to touch on this.

I'm using this for an Android project and the `onSlideChange` method only seems to work when swiping to the last slide. 

To be clearer, I am loading 3 Lottie animations (3 slides)

It seems as if each slide is preloaded (this is is fine)

- Slide 1: First animation plays
- Slide 2: Animation is static (this is because it already played when it was not it view), but I have a `.reset()` and `.play()` method I am calling `onSlideChange`, but nothing happens.
- Slide 3 (last slide): Animation plays as the `.reset()` and `.play()` methods are called in the onSlideChange function.

Why doesn't it work for slide 2?

Many Thanks in advance :)

**Comment by Jacse** [comment] 2020-04-01 13:03
@ymcewen that's hard to say. `onSlideChange` should be called everytime the user moves between pages. Could you share a minimum reproducible repo?

**Comment by Jacse** [comment] 2020-04-10 05:38
Closing this for now. Let me know if you still experience the issue!

**Closed by Jacse** 2020-04-10 05:38 UTC
