### ISSUE TITLE
how to use images in full background?

### ISSUE THREAD

**Issue by dlucidone** [Jacse/react-native-app-intro-slider#6] opened 2017-12-03 18:20 UTC
how to set image in background as full image but at the bottom its showing the default black color?

**Comment by Jacse** [comment] 2017-12-03 18:30
Could you maybe provide some code and/or images of what you are experiencing?

**Comment by dlucidone** [comment] 2017-12-03 18:46
`<AppIntroSlider
        slides={pageArray}
        onDone={this.doneBtnHandle}
      />`

and 

  `const pageArray = [
      {
        key: 'somethun1',
      // title: 'Title 1',
      // text: 'Description.\nSay something cool',
      image: require('../../images/forgotpassword.png'),
      imageStyle: styles.launchImage,
      backgroundColor: 'transparent'
    },]`

![screen shot 2017-12-04 at 12 15 26 am](https://user-images.githubusercontent.com/9256365/33528547-49137a16-d888-11e7-938e-900d610905b8.png)

the height is uncovered although increasing height by few more number its taking full screen then my text is collapsing with the dot circles

**Comment by Jacse** [comment] 2017-12-03 20:01
What I'd do is define a custom `renderItem`-function. If you want I can write a quick working example for you tomorrow. Let me know.

**Comment by dlucidone** [comment] 2017-12-03 21:48
sure can you explain why is it happening?

**Comment by Jacse** [comment] 2017-12-04 08:20
It happens because the standart `DefaultSlide` adds padding in order to make sure content does not go behind the pagination, next-buttons etc.

You could do full-screen background images by writing your own `renderItem`-method as such:

```js

const slides = [
  {
    image: require('./assets/1.jpg'),
  },
  {
    image: require('./assets/2.jpg'),
  },
  {
    key: 'somethun1',
    image: require('./assets/3.jpg'),
  }
];


export default class App extends React.Component {
  _renderItem = props => (
    <Image style={{ flex: 1, width: null, height: null, resizeMode: 'cover'}} source={props.image} />
  );
  render() {
    return (
      <AppIntroSlider
        slides={slides}
        renderItem={this._renderItem}
      />
    );
  }
}
``

**Comment by dlucidone** [comment] 2017-12-04 08:43
Not working, now its more padding from left and right side - 
![screen shot 2017-12-04 at 2 11 48 pm](https://user-images.githubusercontent.com/9256365/33543478-35028934-d8fd-11e7-8d71-a4a677f95192.png)

**Comment by Jacse** [comment] 2017-12-04 08:58
Could you please paste your code and styles?

**Comment by dlucidone** [comment] 2017-12-04 12:40
`/**
 * Launch Screen
 *  - Shows a nice loading screen whilst:
 *  - Preloading any specified app content
 *  - Checking if user is logged in, and redirects from there
 *
 * React Native Starter App
 * https://github.com/mcnamee/react-native-starter-app
 */
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import {
  View,
  Image,
  Alert,
  StatusBar,
  StyleSheet,
  ActivityIndicator,
} from 'react-native';
import { Actions } from 'react-native-router-flux';
import {
  BallIndicator,
  BarIndicator,
  DotIndicator,
  MaterialIndicator,
  PacmanIndicator,
  PulseIndicator,
  SkypeIndicator,
  UIActivityIndicator,
  WaveIndicator
} from 'react-native-indicators';
// Consts and Libs
import { AppStyles, AppSizes } from '@theme/';
import AppIntro from 'react-native-app-intro';
import AppIntroSlider from 'react-native-app-intro-slider';
/* Styles ==================================================================== */
const styles = StyleSheet.create({
  launchImage: {
    width: 375,
    height: 740,
    resizeMode: 'cover',
    backgroundColor: 'transparent'
  },
  image: {
    width: 320,
    height: 320,
  }
});

/* Component ==================================================================== */
class Walkthrough extends Component {
  static componentName = 'AppLaunch';

  static propTypes = {
    login: PropTypes.func.isRequired,
    getRecipes: PropTypes.func.isRequired,
    getMeals: PropTypes.func.isRequired,
    registerAppId:PropTypes.func.isRequired,
    generateAppId:PropTypes.func.isRequired,
    accountId: PropTypes.string,
    appVersion: PropTypes.string,
    platform: PropTypes.string,
    active:PropTypes.bool,
    // appIdAvailable:PropTypes.string,
  }
  constructor(props) {
    super(props);
    // console.log("data in props",props);
      this.state = {
        formValues : {
          accountId: props.accountId,
          appVersion: props.appVersion,
          platform: props.platform,
          active: props.active,
          // appIdAvailable:props.appIdAvailable
        },
      }
  }

  componentDidMount = () => {
    // Show status bar on app launch
    // StatusBar.setHidden(false, true);
  }

  onSkipBtnHandle = (index) => {
    Alert.alert('Skip');
    console.log(index);
  }
  doneBtnHandle = () => {
    // Alert.alert('Done');
    Actions.splash();
  }
  nextBtnHandle = (index) => {
    Alert.alert('Next');
    console.log(index);
  }
  onSlideChangeHandle = (index, total) => {
    console.log(index, total);
  }
  render = () => {
    console.log(AppSizes.screen.width);
    console.log(AppSizes.screen.height)
    const pageArray = [
      {
        key: 'somethun1',
      // title: 'Title 1',
      // text: 'Description.\nSay something cool',
      image: require('../../images/forgotpassword.png'),
      imageStyle: styles.launchImage,
      backgroundColor: 'transparent'
    },
      {
     // title: 'Page 1',
     // description: 'Description 1',
     // img: 'https://goo.gl/Bnc3XP',
     // imgStyle: {
     //   height: AppSizes.screen.width,
     //   width: AppSizes.screen.height,
     // },
     // backgroundColor: '#fa931d',
     // fontColor: '#fff',
     // level: 10,
     key: 'somethun2',
   // title: 'Title 1',
   // text: 'Description.\nSay something cool',
   image: require('../../images/login.png'),
   imageStyle: styles.launchImage,
      backgroundColor: 'transparent'
   }, {
     key: 'somethun3',
   // title: 'Title 1',
   // text: 'Description.\nSay something cool',
   image: require('../../images/accountinfo.png'),
   imageStyle: styles.launchImage,
   backgroundColor: 'transparent'
   }];
    return(
     //  <AppIntro
     //   onNextBtnClick={this.nextBtnHandle}
     //   onDoneBtnClick={this.doneBtnHandle}
     //   onSkipBtnClick={this.onSkipBtnHandle}
     //   onSlideChange={this.onSlideChangeHandle}
     //   pageArray={pageArray}
     // />
     <AppIntroSlider
        slides={pageArray}
        onDone={this.doneBtnHandle}
      />

  )}
}


/* Export Component ==================================================================== */
export default Walkthrough;
`

**Comment by Jacse** [comment] 2017-12-05 16:15
@dlucidone You don't specify a custom `renderItem`-function here as I suggested?

**Comment by wmonecke** [comment] 2017-12-16 10:24
@Jacse Not an issues but thank you for creating this package and maintaining it! Cheers!

**Comment by Jacse** [comment] 2017-12-17 13:46
@wmonecke No worries, thanks for the kind words!

**Comment by Jacse** [comment] 2017-12-17 13:47
@dlucidone I'm going to close this since the issue is on your end. If you disagree or need more help please don't hesitate to re-open or reply.

**Closed by Jacse** 2017-12-17 13:47 UTC
Labels: question

**Comment by dlucidone** [comment] 2017-12-21 10:34
@Jacse  It Worked !

**Comment by pbbhopp** [comment] 2018-08-19 15:37
Worked with width: width, height: height!

**Comment by rodionovich221** [comment] 2019-07-29 11:24
> @Jacse It Worked !

Hi @Jacse Could you elaborate on how you make it work?

**Comment by Jacse** [comment] 2019-07-29 19:44
@rodionovich221 please open a new issue with screenshots and code. The way the library works now is a little different from when this issue was created.
