### ISSUE TITLE
ReferenceError: ReferenceError: Can't find variable: style

### ISSUE THREAD

**Issue by lascooter** [Jacse/react-native-app-intro-slider#110] opened 2019-04-20 20:33 UTC
I've tried to incorporate this into an app my group is working on and I keep running into this error.

![image](https://user-images.githubusercontent.com/11504346/56462021-fd215400-6389-11e9-852b-e1be5c204885.png)

Any idea on how to go go about it?

**Comment by Jacse** [comment] 2019-04-21 05:39
Looks like you are trying to access an undefined variable. I'm guessing your passing a style-prop but haven't defined the style variable.

**Comment by Jacse** [comment] 2019-04-26 06:49
I'm going to close this seems it looks like an issue on your end and not with the component. Let me know if you disagree or have other issues.

**Closed by Jacse** 2019-04-26 06:49 UTC

**Comment by UnSensei** [comment] 2020-01-24 09:28
@Jacse on the Readme, in the first example the style props for <Text> inside the _renderItems has style.text. Copying it from the example is the cause for this.
